"""Add event idempotency table

Revision ID: 699868a51b34
Revises: f0b007cd3c40
Create Date: 2026-06-09 08:12:36.324798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '699868a51b34'
down_revision: Union[str, None] = 'f0b007cd3c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_idempotency_keys',
    sa.Column('key', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_idempotency_keys')
    # ### end Alembic commands ###
