"""Add blocking reasons and tickets tables

Revision ID: f0b007cd3c40
Revises: 
Create Date: 2026-06-09 06:50:50.162162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0b007cd3c40'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocking_reasons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('hard_block', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocking_reasons_code'), 'blocking_reasons', ['code'], unique=True)
    
    # Засеиваем канонические причины блокировки
    from src.db.models import SEED_REASONS
    import uuid
    seed_data = [
        {
            "id": uuid.UUID(r["id"]),
            "code": r["code"],
            "title": r["title"],
            "description": None,
            "hard_block": r["hard_block"],
            "is_active": True
        }
        for r in SEED_REASONS
    ]
    blocking_reasons_table = sa.table(
        'blocking_reasons',
        sa.column('id', sa.Uuid),
        sa.column('code', sa.String),
        sa.column('title', sa.String),
        sa.column('description', sa.String),
        sa.column('hard_block', sa.Boolean),
        sa.column('is_active', sa.Boolean)
    )
    op.bulk_insert(blocking_reasons_table, seed_data)

    op.create_table('tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('seller_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('queue_priority', sa.Integer(), nullable=False),
    sa.Column('assigned_moderator_id', sa.Uuid(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('claim_expires_at', sa.DateTime(), nullable=True),
    sa.Column('decision_at', sa.DateTime(), nullable=True),
    sa.Column('decision_comment', sa.String(length=2000), nullable=True),
    sa.Column('json_before', sa.JSON(), nullable=True),
    sa.Column('json_after', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_product_id'), 'tickets', ['product_id'], unique=False)
    op.create_index(op.f('ix_tickets_seller_id'), 'tickets', ['seller_id'], unique=False)
    op.create_table('ticket_blocking_reasons',
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('reason_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['reason_id'], ['blocking_reasons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id', 'reason_id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_blocking_reasons')
    op.drop_index(op.f('ix_tickets_seller_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_product_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_blocking_reasons_code'), table_name='blocking_reasons')
    op.drop_table('blocking_reasons')
    # ### end Alembic commands ###
